name: Trigger AI Analysis
#testtir
on:
  workflow_dispatch:  # ✅ Manuel çalıştırma aktif
  [push]:
    branches:
      - main  # 🔥 Ana projeye push yapılınca çalışsın

jobs:
  trigger_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: 🔥 AI Analysis Action'ı Tetikle
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.ANALYSIS_TRIGGER_TOKEN }}" \
          https://api.github.com/repos/CagriYolyapar/CoreSemanticKernelGithub/dispatches \
          -d '{"event_type": "trigger-ai-analysis"}'
